import { useMemo, useState } from "react";
import JSZip from "jszip";
import { Vek } from "../lib/engine.js";
import { FrameworkTabs, CodeBlock, Icon, CoffeeModal, isCoffeeSuppressed } from "../components.jsx";

function toPascal(s) {
  return s.replace(/[^a-z0-9]+/gi, " ").trim().split(" ").filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join("");
}

function extForFramework(framework, ts) {
  if (framework === "vue") return "vue";
  if (framework === "svelte") return "svelte";
  return ts ? "tsx" : "jsx";
}

function indexExt(framework, ts) {
  if (framework === "vue" || framework === "svelte") return ts ? "ts" : "js";
  return ts ? "ts" : "js";
}

function buildIndex(icons, framework, ts) {
  const ext = extForFramework(framework, ts);
  if (framework === "react" || framework === "solid") {
    return icons
      .map((i) => `export { ${i.componentName} } from "./${i.componentName}";`)
      .join("\n") + "\n";
  }
  // vue / svelte — default export per SFC, re-export as named
  return icons
    .map((i) => `export { default as ${i.componentName} } from "./${i.componentName}.${ext}";`)
    .join("\n") + "\n";
}

function buildReadme(icons, framework, ts) {
  const ext = extForFramework(framework, ts);
  const example = icons[0]?.componentName ?? "MyIcon";
  return `# Icon library

Generated by Vectorio — ${icons.length} ${framework} components${ts ? " with TypeScript" : ""}.

## Usage

\`\`\`${ts ? "ts" : "js"}
import { ${example} } from "./icons";
\`\`\`

Tree-shakable named exports — only the icons you import end up in your bundle.

## Contents

- \`index.${indexExt(framework, ts)}\` — barrel export
- \`package.json\` — ships with \`"sideEffects": false\` for aggressive tree-shaking
- ${icons.length} component file${icons.length === 1 ? "" : "s"} (\`*.${ext}\`)

## Props

- \`size\` — number or string, defaults to \`24\`
- \`color\` — any CSS color, defaults to \`currentColor\` (inherits from parent text color)
- \`strokeWidth\` — outline icons only

Multi-color icons keep their original palette; the \`color\` prop is disabled for those automatically.
`;
}

function buildPackageJson(icons, framework, ts) {
  const ext = extForFramework(framework, ts);
  const entry = `index.${indexExt(framework, ts)}`;
  const pkg = {
    name: "my-icon-library",
    version: "0.1.0",
    description: `${icons.length} ${framework} icon components generated by Vectorio`,
    type: "module",
    main: entry,
    module: entry,
    sideEffects: false,
    files: [entry, `*.${ext}`, ts ? "*.d.ts" : null].filter(Boolean),
    keywords: ["icons", framework, "svg", "components"],
    peerDependencies:
      framework === "react"  ? { react: ">=17" } :
      framework === "vue"    ? { vue: ">=3" } :
      framework === "svelte" ? { svelte: ">=4" } :
      framework === "solid"  ? { "solid-js": ">=1.6" } : {},
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

// Validate an SVG string quickly. Full Vek.parseSvg is heavy to run 500x synchronously.
function isValidSvg(svg) {
  if (!svg || svg.length < 10) return false;
  const t = svg.trim().toLowerCase();
  if (!t.startsWith("<?xml") && !t.startsWith("<!doctype") && !t.startsWith("<svg") && !t.startsWith("<!--")) return false;
  return /<svg[\s>]/i.test(t);
}

// macOS Finder zips include AppleDouble metadata under __MACOSX/ and ._-prefixed
// shadows next to real files. They look like .svg by extension but are binary junk.
function isMacJunkPath(path) {
  if (path.startsWith("__MACOSX/") || path.includes("/__MACOSX/")) return true;
  const base = path.split("/").pop() || "";
  if (base.startsWith("._")) return true;
  if (base === ".DS_Store" || base === "Thumbs.db") return true;
  return false;
}

async function parseZipFile(file, skipped) {
  const zip = await JSZip.loadAsync(file);
  const entries = [];
  for (const [path, entry] of Object.entries(zip.files)) {
    if (entry.dir) continue;
    if (isMacJunkPath(path)) continue;
    const lower = path.toLowerCase();
    const base = path.split("/").pop();
    if (!lower.endsWith(".svg")) {
      if (!lower.endsWith("/") && !base.startsWith(".")) {
        skipped.push({ name: `${file.name} · ${path}`, reason: "not an SVG" });
      }
      continue;
    }
    const svg = await entry.async("string");
    if (!isValidSvg(svg)) {
      skipped.push({ name: `${file.name} · ${path}`, reason: "invalid SVG markup" });
      continue;
    }
    const nameBase = base.replace(/\.svg$/i, "");
    // Preserve folder to namespace duplicates — outline/arrow.svg → arrow (folder: outline)
    const folder = path.includes("/") ? path.split("/").slice(0, -1).join("/") : "";
    entries.push({
      id: crypto.randomUUID(),
      name: nameBase,
      folder,
      svg,
      componentName: toPascal(nameBase) + "Icon",
    });
  }
  return entries;
}

// Walk a dropped directory tree via the webkit FileSystem API. Returns flat File[]
// with `webkitRelativePath` populated so folder-namespacing keeps working.
async function collectDroppedFiles(dataTransfer) {
  const items = dataTransfer.items;
  if (!items || !items.length || typeof items[0].webkitGetAsEntry !== "function") {
    return Array.from(dataTransfer.files || []);
  }
  const entries = [];
  for (const item of items) {
    const entry = item.webkitGetAsEntry?.();
    if (entry) entries.push(entry);
  }
  if (!entries.length) return Array.from(dataTransfer.files || []);

  const out = [];
  const walk = async (entry, prefix) => {
    if (isMacJunkPath(entry.name) || isMacJunkPath(prefix + entry.name)) return;
    if (entry.isFile) {
      const file = await new Promise((res, rej) => entry.file(res, rej));
      // Stamp a relative path so existing folder-detection in ingestFiles works.
      try {
        Object.defineProperty(file, "webkitRelativePath", {
          value: prefix + entry.name,
          configurable: true,
        });
      } catch { /* webkitRelativePath is read-only on some platforms; folder will just be empty */ }
      out.push(file);
      return;
    }
    if (entry.isDirectory) {
      const reader = entry.createReader();
      // readEntries returns at most ~100 entries per call; loop until empty.
      const all = [];
      while (true) {
        const batch = await new Promise((res, rej) => reader.readEntries(res, rej));
        if (!batch.length) break;
        all.push(...batch);
      }
      for (const child of all) await walk(child, prefix + entry.name + "/");
    }
  };
  for (const entry of entries) await walk(entry, "");
  return out;
}

async function ingestFiles(fileList) {
  const files = Array.from(fileList || []);
  const out = [];
  const skipped = [];
  for (const f of files) {
    const lower = f.name.toLowerCase();
    if (isMacJunkPath(f.webkitRelativePath || f.name)) continue;
    if (lower.endsWith(".svg")) {
      const svg = await f.text();
      if (!isValidSvg(svg)) {
        skipped.push({ name: f.name, reason: "invalid SVG markup" });
        continue;
      }
      const name = f.name.replace(/\.svg$/i, "");
      // webkitRelativePath preserves folder when a directory is dropped.
      const rel = f.webkitRelativePath || "";
      const folder = rel.includes("/") ? rel.split("/").slice(0, -1).join("/") : "";
      out.push({ id: crypto.randomUUID(), name, folder, svg, componentName: toPascal(name) + "Icon" });
    } else if (lower.endsWith(".zip")) {
      const fromZip = await parseZipFile(f, skipped);
      out.push(...fromZip);
    } else {
      skipped.push({ name: f.name, reason: "not an SVG or ZIP" });
    }
  }
  return { out, skipped };
}

// Resolve duplicate component names by folder-prefixing the ones that collide.
// Two icons named "Arrow" in different folders become "ArrowOutline" / "ArrowSolid".
function namespaceCollisions(icons) {
  const counts = new Map();
  for (const i of icons) counts.set(i.componentName, (counts.get(i.componentName) || 0) + 1);
  return icons.map((i) => {
    if ((counts.get(i.componentName) || 0) <= 1 || !i.folder) return i;
    const folderTag = toPascal(i.folder.split("/").pop() || "");
    if (!folderTag) return i;
    // Strip "Icon" suffix from base, add folder, re-add Icon suffix: ArrowIcon → ArrowOutlineIcon
    const stripped = i.componentName.replace(/Icon$/, "");
    return { ...i, componentName: stripped + folderTag + "Icon" };
  });
}

export function Batch() {
  const [icons, setIcons] = useState([]);

  const loadSamples = () => {
    setIcons(Vek.SAMPLE_ICONS.map((i) => ({
      ...i,
      id: crypto.randomUUID(),
      componentName: toPascal(i.name) + "Icon",
      sample: true,
    })));
  };
  const [drag, setDrag] = useState(false);
  const [framework, setFramework] = useState("react");
  const [ts, setTs] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [showIndex, setShowIndex] = useState(false);
  const [freshIds, setFreshIds] = useState(() => new Set());
  const [skipped, setSkipped] = useState([]);
  const [bulkStrip, setBulkStrip] = useState("");
  const [bulkPrefix, setBulkPrefix] = useState("");
  const [bulkSuffix, setBulkSuffix] = useState("Icon");
  const [autoNamespace, setAutoNamespace] = useState(true);
  const [filter, setFilter] = useState("");
  const [copiedId, setCopiedId] = useState(null);
  const [coffeeOpen, setCoffeeOpen] = useState(false);

  const addResult = (result) => {
    const { out: added, skipped: newSkipped } = result;
    if (newSkipped.length) setSkipped(newSkipped);
    else setSkipped([]);
    if (!added.length) return;
    const next = autoNamespace ? namespaceCollisions(added) : added;
    setIcons((cur) => {
      const keep = cur.some((i) => !i.sample) ? cur : [];
      // Dedupe by id — StrictMode double-invokes this updater in dev; without
      // dedupe a single drop ends up appended twice.
      const seen = new Set();
      const combined = [];
      for (const item of [...next, ...keep]) {
        if (seen.has(item.id)) continue;
        seen.add(item.id);
        combined.push(item);
      }
      // Re-run namespacing across the combined set so a new drop resolves against existing too.
      return autoNamespace ? namespaceCollisions(combined) : combined;
    });
    setFreshIds(new Set(next.map((a) => a.id)));
    setTimeout(() => setFreshIds(new Set()), 1500);
  };

  const onDrop = async (e) => {
    e.preventDefault();
    setDrag(false);
    const files = await collectDroppedFiles(e.dataTransfer);
    addResult(await ingestFiles(files));
  };

  const onPickFiles = async (e) => {
    addResult(await ingestFiles(e.target.files));
    e.target.value = "";
  };

  const updateName = (id, newName) => {
    setIcons(icons.map((i) => (i.id === id ? { ...i, componentName: newName } : i)));
  };

  const removeIcon = (id) => setIcons(icons.filter((i) => i.id !== id));

  // Bulk apply the rename rules to every (non-sample) icon. Rules are applied to the
  // original file basename, not to the current componentName — so re-running is idempotent.
  const applyBulkRename = () => {
    setIcons((cur) => cur.map((i) => {
      let base = i.name || "";
      if (bulkStrip) {
        // Treat bulkStrip as a literal substring to strip from the start (most common case).
        const esc = bulkStrip.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        base = base.replace(new RegExp(`^${esc}`, "i"), "");
      }
      let pascal = toPascal(base);
      if (bulkPrefix) pascal = toPascal(bulkPrefix) + pascal;
      if (bulkSuffix) pascal = pascal + bulkSuffix;
      return { ...i, componentName: pascal };
    }));
  };

  const totalBytes = icons.reduce((s, i) => s + new Blob([i.svg]).size, 0);
  const avgBytes = icons.length ? Math.round(totalBytes / icons.length) : 0;

  const filteredIcons = useMemo(() => {
    const q = filter.trim().toLowerCase();
    if (!q) return icons;
    return icons.filter((i) =>
      (i.componentName || "").toLowerCase().includes(q) ||
      (i.name || "").toLowerCase().includes(q) ||
      (i.folder || "").toLowerCase().includes(q)
    );
  }, [icons, filter]);

  const copyOne = async (icon) => {
    const parsed = Vek.parseSvg(icon.svg);
    if (!parsed.ok) return;
    const code = Vek.generate(framework, parsed, {
      name: icon.componentName, ts, tw: false,
      props: { color: true, size: true, stroke: false },
    });
    try { await navigator.clipboard.writeText(code); } catch { /* noop */ }
    setCopiedId(icon.id);
    setTimeout(() => setCopiedId((id) => id === icon.id ? null : id), 1200);
  };

  const downloadOne = (icon) => {
    const parsed = Vek.parseSvg(icon.svg);
    if (!parsed.ok) return;
    const code = Vek.generate(framework, parsed, {
      name: icon.componentName, ts, tw: false,
      props: { color: true, size: true, stroke: false },
    });
    const ext = extForFramework(framework, ts);
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${icon.componentName}.${ext}`; a.click();
    URL.revokeObjectURL(url);
  };

  // Detect name collisions — two icons sharing a componentName would overwrite each
  // other in the zip and produce a broken barrel export.
  const duplicateNames = useMemo(() => {
    const counts = new Map();
    for (const i of icons) counts.set(i.componentName, (counts.get(i.componentName) || 0) + 1);
    return new Set([...counts.entries()].filter(([, n]) => n > 1).map(([k]) => k));
  }, [icons]);

  // Detect invalid names (empty or starting with digit — both break JS imports).
  const invalidNames = useMemo(() => {
    return new Set(icons.filter((i) => !i.componentName || /^\d/.test(i.componentName)).map((i) => i.componentName));
  }, [icons]);

  const hasIssues = duplicateNames.size > 0 || invalidNames.size > 0;

  const indexSource = useMemo(() => buildIndex(icons, framework, ts), [icons, framework, ts]);
  const targetExt = extForFramework(framework, ts);

  const generateZip = async () => {
    if (!icons.length || downloading) return;
    setDownloading(true);
    try {
      const zip = new JSZip();
      const ext = extForFramework(framework, ts);
      const root = zip.folder("icons");

      for (const icon of icons) {
        const parsed = Vek.parseSvg(icon.svg);
        if (!parsed.ok) continue;
        const code = Vek.generate(framework, parsed, {
          name: icon.componentName,
          ts,
          tw: false,
          props: { color: true, size: true, stroke: false },
        });
        root.file(`${icon.componentName}.${ext}`, code);
      }
      root.file(`index.${indexExt(framework, ts)}`, indexSource);
      root.file("README.md", buildReadme(icons, framework, ts));
      root.file("package.json", buildPackageJson(icons, framework, ts));

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "icons-library.zip";
      a.click();
      URL.revokeObjectURL(url);

      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 1600);
      // Delay so the OS save dialog has time to close before our modal appears
      // — otherwise the modal opens behind the dialog and gets missed.
      if (!isCoffeeSuppressed()) setTimeout(() => setCoffeeOpen(true), 600);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="batch">
      <div className="batch-head">
        <div>
          <h1>Build your own <em>icon library.</em></h1>
          <p className="sub">Drop your SVGs — a folder, a .zip, or a handful of files — and Vectorio turns them into a tree-shakable component library with typed exports, a generated index, and a README. Your icons, your names, your framework.</p>
        </div>
        <div className="nav-meta" style={{ textAlign: "right" }}>
          <span>runs locally · nothing uploaded</span>
        </div>
      </div>

      <div
        className={`batch-drop ${drag ? "drag" : ""}`}
        onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
        onDragLeave={() => setDrag(false)}
        onDrop={onDrop}
        onClick={() => document.getElementById("batch-file-input").click()}
      >
        <input
          id="batch-file-input"
          type="file"
          accept=".svg,.zip"
          multiple
          style={{ display: "none" }}
          onChange={onPickFiles}
        />
        <div>
          <div className="lead">Drop SVGs, a folder, or a .zip</div>
          <div className="hint">any size · processes in-browser · nothing leaves this page</div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--fg-muted)", fontSize: 13, fontFamily: "var(--mono)" }}>
          click to browse {Icon.arrow}
        </div>
      </div>

      {skipped.length > 0 && (
        <div className="notice notice-warn" style={{ marginTop: 16 }}>
          <strong>{skipped.length} file{skipped.length === 1 ? "" : "s"} skipped</strong> — {skipped.slice(0, 5).map((s, i) => (
            <span key={i}><code style={{ marginRight: 4 }}>{s.name}</code>({s.reason}){i < Math.min(skipped.length, 5) - 1 ? ", " : ""}</span>
          ))}
          {skipped.length > 5 && <span> …and {skipped.length - 5} more.</span>}
          <button
            className="toggle-pill"
            style={{ marginLeft: 12, fontSize: 10 }}
            onClick={() => setSkipped([])}
          >dismiss</button>
        </div>
      )}

      <div className="batch-stats">
        <div className="batch-stat">
          <span className="k">Icons queued</span>
          <span className="v"><em>{icons.length}</em></span>
        </div>
        <div className="batch-stat">
          <span className="k">Total size</span>
          <span className="v">{(totalBytes / 1024).toFixed(1)}<span style={{ fontSize: 14, color: "var(--fg-faint)", marginLeft: 4 }}>KB</span></span>
        </div>
        <div className="batch-stat">
          <span className="k">Avg per icon</span>
          <span className="v">{avgBytes}<span style={{ fontSize: 14, color: "var(--fg-faint)", marginLeft: 4 }}>B</span></span>
        </div>
        <div className="batch-stat">
          <span className="k">Output</span>
          <span className="v" style={{ fontFamily: "var(--mono)", fontSize: 16 }}>icons-library.zip</span>
        </div>
      </div>

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16, gap: 16, flexWrap: "wrap" }}>
        <div className="section-title" style={{ display: "inline-flex", alignItems: "center", gap: 12 }}>
          <span>{icons.some((i) => i.sample) ? "Preview — sample icons below" : `Library contents · ${icons.length}`}</span>
          {icons.length > 6 && (
            <input
              className="batch-filter"
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              placeholder="Filter by name or folder…"
              spellCheck={false}
            />
          )}
          {filter && filteredIcons.length !== icons.length && (
            <span style={{ fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-faint)", textTransform: "none", letterSpacing: 0 }}>
              {filteredIcons.length} of {icons.length} match
            </span>
          )}
        </div>
        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          <span style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-faint)", letterSpacing: "0.04em" }}>
            output · <span style={{ color: "var(--accent)" }}>.{targetExt}</span>
          </span>
          <FrameworkTabs value={framework} onChange={setFramework} />
          <button
            className={`toggle-pill switch ${ts ? "on" : ""}`}
            onClick={() => setTs(!ts)}
            aria-pressed={ts}
          >
            <span className="dot" />
            <span>TypeScript</span>
            <span className="state">{ts ? "on" : "off"}</span>
          </button>
        </div>
      </div>

      {icons.some((i) => i.sample) && (
        <div className="sample-banner">
          <div>
            <div className="lead">These are samples so you can see how it looks.</div>
            <div className="hint">Drop your own SVGs above — or start from scratch.</div>
          </div>
          <button className="btn-secondary" onClick={() => setIcons([])}>Clear samples · start empty</button>
        </div>
      )}

      {hasIssues && (
        <div className="notice notice-warn" style={{ marginBottom: 16 }}>
          <strong>{duplicateNames.size + invalidNames.size} issue{(duplicateNames.size + invalidNames.size) === 1 ? "" : "s"} need attention</strong> — rename the highlighted icons below before downloading.
          {duplicateNames.size > 0 && <div style={{ marginTop: 4 }}>· {duplicateNames.size} duplicate name{duplicateNames.size === 1 ? "" : "s"}: {[...duplicateNames].map((n) => <code key={n} style={{ marginRight: 6 }}>{n}</code>)}</div>}
          {invalidNames.size > 0 && <div style={{ marginTop: 4 }}>· {invalidNames.size} invalid name{invalidNames.size === 1 ? "" : "s"} (empty or starts with digit)</div>}
        </div>
      )}

      {icons.length === 0 && (
        <div className="batch-empty">
          <div className="batch-empty-lead">No icons yet</div>
          <div className="batch-empty-sub">Drop your SVGs above to begin — or</div>
          <button className="batch-empty-link" onClick={loadSamples}>
            see it with {Vek.SAMPLE_ICONS.length} sample icons {Icon.arrow}
          </button>
        </div>
      )}

      {icons.length > 0 && (
        <div className="bulk-rename">
          <div className="bulk-rename-label">Bulk rename</div>
          <div className="bulk-rename-fields">
            <label>
              <span>Strip prefix</span>
              <input
                value={bulkStrip}
                onChange={(e) => setBulkStrip(e.target.value)}
                placeholder="icon-"
                spellCheck={false}
              />
            </label>
            <label>
              <span>Add prefix</span>
              <input
                value={bulkPrefix}
                onChange={(e) => setBulkPrefix(e.target.value)}
                placeholder=""
                spellCheck={false}
              />
            </label>
            <label>
              <span>Suffix</span>
              <input
                value={bulkSuffix}
                onChange={(e) => setBulkSuffix(e.target.value)}
                placeholder="Icon"
                spellCheck={false}
              />
            </label>
            <button
              className={`toggle-pill switch ${autoNamespace ? "on" : ""}`}
              onClick={() => setAutoNamespace(!autoNamespace)}
              aria-pressed={autoNamespace}
              title="When two icons share a name, append the folder name to disambiguate"
            >
              <span className="dot" />
              <span>Auto-namespace folders</span>
              <span className="state">{autoNamespace ? "on" : "off"}</span>
            </button>
            <button className="btn-secondary" onClick={applyBulkRename}>Apply to all</button>
          </div>
          <div className="bulk-rename-hint">
            Rules re-run from the original filenames — safe to apply repeatedly.
          </div>
        </div>
      )}

      <div className="icon-grid">
        {filteredIcons.map((icon) => {
          const dup = duplicateNames.has(icon.componentName);
          const invalid = !icon.componentName || /^\d/.test(icon.componentName);
          const flagged = dup || invalid;
          return (
          <div className={`icon-cell ${freshIds.has(icon.id) ? "fresh" : ""} ${flagged ? "flagged" : ""}`} key={icon.id}>
            <div className="icon-thumb" dangerouslySetInnerHTML={{ __html: icon.svg }} />
            <div className="icon-info">
              <input
                className="icon-name"
                value={icon.componentName}
                onChange={(e) => updateName(icon.id, e.target.value.replace(/[^a-zA-Z0-9]/g, ""))}
                spellCheck={false}
                aria-invalid={flagged}
              />
              <div className="icon-src" style={flagged ? { color: "oklch(0.55 0.15 45)" } : undefined}>
                {flagged ? (dup ? "duplicate name" : "invalid name") : `${icon.name}.svg`}
              </div>
            </div>
            <div className="icon-actions">
              <button
                className="icon-act"
                onClick={() => copyOne(icon)}
                title={`Copy ${icon.componentName} as ${framework}`}
                disabled={flagged}
              >
                {copiedId === icon.id ? Icon.check : Icon.copy}
              </button>
              <button
                className="icon-act"
                onClick={() => downloadOne(icon)}
                title={`Download ${icon.componentName}.${targetExt}`}
                disabled={flagged}
              >
                {Icon.download}
              </button>
              <button
                className="icon-act icon-act-remove"
                onClick={() => removeIcon(icon.id)}
                title="Remove"
              >×</button>
            </div>
          </div>
          );
        })}
        {filter && filteredIcons.length === 0 && (
          <div className="batch-empty" style={{ gridColumn: "1 / -1" }}>
            <div className="batch-empty-lead">No matches</div>
            <div className="batch-empty-sub">Nothing in the library matches "{filter}"</div>
            <button className="batch-empty-link" onClick={() => setFilter("")}>Clear filter {Icon.arrow}</button>
          </div>
        )}
      </div>

      {showIndex && (
        <div style={{ marginTop: 24, display: "flex", flexDirection: "column", gap: 10 }}>
          <div className="section-title">
            <span>index.{indexExt(framework, ts)}</span>
            <button className="toggle-pill" onClick={() => setShowIndex(false)}>Hide</button>
          </div>
          <CodeBlock code={indexSource} lang={framework} />
        </div>
      )}

      <div className="batch-actions">
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-faint)", letterSpacing: "0.04em" }}>
          → generates <span style={{ color: "var(--fg-muted)" }}>icons/</span> with {icons.length} component {icons.length === 1 ? "file" : "files"}, <span style={{ color: "var(--fg-muted)" }}>index.{indexExt(framework, ts)}</span>, <span style={{ color: "var(--fg-muted)" }}>package.json</span>, and a README
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button className="btn-secondary" onClick={() => setShowIndex((v) => !v)}>
            {showIndex ? "Hide index file" : "Preview index file"}
          </button>
          <button
            className="btn-primary"
            onClick={generateZip}
            disabled={!icons.length || downloading || hasIssues}
            title={hasIssues ? "Fix the flagged names above first" : undefined}
          >
            {downloaded ? Icon.check : Icon.download}
            <span>{downloading ? "Generating…" : downloaded ? "Downloaded" : hasIssues ? "Fix issues to download" : "Download icon library"}</span>
          </button>
        </div>
      </div>
      <CoffeeModal open={coffeeOpen} onClose={() => setCoffeeOpen(false)} />
    </div>
  );
}
