import { useMemo, useState } from "react";
import JSZip from "jszip";
import { Vek } from "../lib/engine.js";
import { FrameworkTabs, CodeBlock, Icon } from "../components.jsx";

function toPascal(s) {
  return s.replace(/[^a-z0-9]+/gi, " ").trim().split(" ").filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase()).join("");
}

function extForFramework(framework, ts) {
  if (framework === "vue") return "vue";
  if (framework === "svelte") return "svelte";
  return ts ? "tsx" : "jsx";
}

function indexExt(framework, ts) {
  if (framework === "vue" || framework === "svelte") return ts ? "ts" : "js";
  return ts ? "ts" : "js";
}

function buildIndex(icons, framework, ts) {
  const ext = extForFramework(framework, ts);
  if (framework === "react" || framework === "solid") {
    return icons
      .map((i) => `export { ${i.componentName} } from "./${i.componentName}";`)
      .join("\n") + "\n";
  }
  // vue / svelte — default export per SFC, re-export as named
  return icons
    .map((i) => `export { default as ${i.componentName} } from "./${i.componentName}.${ext}";`)
    .join("\n") + "\n";
}

function buildReadme(icons, framework, ts) {
  const ext = extForFramework(framework, ts);
  const example = icons[0]?.componentName ?? "MyIcon";
  return `# Icon library

Generated by Vektorio — ${icons.length} ${framework} components${ts ? " with TypeScript" : ""}.

## Usage

\`\`\`${ts ? "ts" : "js"}
import { ${example} } from "./icons";
\`\`\`

## Contents

- \`index.${indexExt(framework, ts)}\` — barrel export
- ${icons.length} component file${icons.length === 1 ? "" : "s"} (\`*.${ext}\`)
`;
}

async function parseZipFile(file) {
  const zip = await JSZip.loadAsync(file);
  const entries = [];
  for (const [path, entry] of Object.entries(zip.files)) {
    if (entry.dir) continue;
    if (!path.toLowerCase().endsWith(".svg")) continue;
    const svg = await entry.async("string");
    const base = path.split("/").pop().replace(/\.svg$/i, "");
    entries.push({
      id: crypto.randomUUID(),
      name: base,
      svg,
      componentName: toPascal(base) + "Icon",
    });
  }
  return entries;
}

async function ingestFiles(fileList) {
  const files = Array.from(fileList || []);
  const out = [];
  for (const f of files) {
    if (f.name.toLowerCase().endsWith(".svg")) {
      const svg = await f.text();
      const name = f.name.replace(/\.svg$/i, "");
      out.push({ id: crypto.randomUUID(), name, svg, componentName: toPascal(name) + "Icon" });
    } else if (f.name.toLowerCase().endsWith(".zip")) {
      const fromZip = await parseZipFile(f);
      out.push(...fromZip);
    }
  }
  return out;
}

export function Batch() {
  const [icons, setIcons] = useState(() => Vek.SAMPLE_ICONS.map((i) => ({ ...i, id: crypto.randomUUID(), componentName: toPascal(i.name) + "Icon", sample: true })));
  const [drag, setDrag] = useState(false);
  const [framework, setFramework] = useState("react");
  const [ts, setTs] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [showIndex, setShowIndex] = useState(false);
  const [freshIds, setFreshIds] = useState(() => new Set());

  const addIcons = (added) => {
    if (!added.length) return;
    // First real drop clears samples so users see their own icons immediately
    setIcons((cur) => {
      const keep = cur.some((i) => !i.sample) ? cur : [];
      return [...added, ...keep];
    });
    setFreshIds(new Set(added.map((a) => a.id)));
    setTimeout(() => setFreshIds(new Set()), 1500);
  };

  const onDrop = async (e) => {
    e.preventDefault();
    setDrag(false);
    addIcons(await ingestFiles(e.dataTransfer.files));
  };

  const onPickFiles = async (e) => {
    addIcons(await ingestFiles(e.target.files));
    e.target.value = "";
  };

  const updateName = (id, newName) => {
    setIcons(icons.map((i) => (i.id === id ? { ...i, componentName: newName } : i)));
  };

  const removeIcon = (id) => setIcons(icons.filter((i) => i.id !== id));

  const totalBytes = icons.reduce((s, i) => s + new Blob([i.svg]).size, 0);
  const avgBytes = icons.length ? Math.round(totalBytes / icons.length) : 0;

  const indexSource = useMemo(() => buildIndex(icons, framework, ts), [icons, framework, ts]);
  const targetExt = extForFramework(framework, ts);

  const generateZip = async () => {
    if (!icons.length || downloading) return;
    setDownloading(true);
    try {
      const zip = new JSZip();
      const ext = extForFramework(framework, ts);
      const root = zip.folder("icons");

      for (const icon of icons) {
        const parsed = Vek.parseSvg(icon.svg);
        if (!parsed.ok) continue;
        const code = Vek.generate(framework, parsed, {
          name: icon.componentName,
          ts,
          tw: false,
          props: { color: true, size: true, stroke: false },
        });
        root.file(`${icon.componentName}.${ext}`, code);
      }
      root.file(`index.${indexExt(framework, ts)}`, indexSource);
      root.file("README.md", buildReadme(icons, framework, ts));

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "icons-library.zip";
      a.click();
      URL.revokeObjectURL(url);

      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 1600);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="batch">
      <div className="batch-head">
        <div>
          <h1>Build your own <em>icon library.</em></h1>
          <p className="sub">Drop your SVGs — a folder, a .zip, or a handful of files — and Vektorio turns them into a tree-shakable component library with typed exports, a generated index, and a README. Your icons, your names, your framework.</p>
        </div>
        <div className="nav-meta" style={{ textAlign: "right" }}>
          <span>runs locally · nothing uploaded</span>
        </div>
      </div>

      <div
        className={`batch-drop ${drag ? "drag" : ""}`}
        onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
        onDragLeave={() => setDrag(false)}
        onDrop={onDrop}
        onClick={() => document.getElementById("batch-file-input").click()}
      >
        <input
          id="batch-file-input"
          type="file"
          accept=".svg,.zip"
          multiple
          style={{ display: "none" }}
          onChange={onPickFiles}
        />
        <div>
          <div className="lead">Drop SVGs, a folder, or a .zip</div>
          <div className="hint">any size · processes in-browser · nothing leaves this page</div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--fg-muted)", fontSize: 13, fontFamily: "var(--mono)" }}>
          click to browse {Icon.arrow}
        </div>
      </div>

      <div className="batch-stats">
        <div className="batch-stat">
          <span className="k">Icons queued</span>
          <span className="v"><em>{icons.length}</em></span>
        </div>
        <div className="batch-stat">
          <span className="k">Total size</span>
          <span className="v">{(totalBytes / 1024).toFixed(1)}<span style={{ fontSize: 14, color: "var(--fg-faint)", marginLeft: 4 }}>KB</span></span>
        </div>
        <div className="batch-stat">
          <span className="k">Avg per icon</span>
          <span className="v">{avgBytes}<span style={{ fontSize: 14, color: "var(--fg-faint)", marginLeft: 4 }}>B</span></span>
        </div>
        <div className="batch-stat">
          <span className="k">Output</span>
          <span className="v" style={{ fontFamily: "var(--mono)", fontSize: 16 }}>icons-library.zip</span>
        </div>
      </div>

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
        <div className="section-title">
          {icons.some((i) => i.sample) ? "Preview — sample icons below" : `Library contents · ${icons.length}`}
        </div>
        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          <span style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-faint)", letterSpacing: "0.04em" }}>
            output · <span style={{ color: "var(--accent)" }}>.{targetExt}</span>
          </span>
          <FrameworkTabs value={framework} onChange={setFramework} />
          <button
            className={`toggle-pill switch ${ts ? "on" : ""}`}
            onClick={() => setTs(!ts)}
            aria-pressed={ts}
          >
            <span className="dot" />
            <span>TypeScript</span>
            <span className="state">{ts ? "on" : "off"}</span>
          </button>
        </div>
      </div>

      {icons.some((i) => i.sample) && (
        <div className="sample-banner">
          <div>
            <div className="lead">These are samples so you can see how it looks.</div>
            <div className="hint">Drop your own SVGs above — or start from scratch.</div>
          </div>
          <button className="btn-secondary" onClick={() => setIcons([])}>Clear samples · start empty</button>
        </div>
      )}

      {icons.length === 0 && (
        <div style={{ padding: "48px 0", textAlign: "center", fontFamily: "var(--mono)", fontSize: 12, color: "var(--fg-faint)", letterSpacing: "0.06em", borderTop: "1px solid var(--rule)", borderBottom: "1px solid var(--rule)" }}>
          no icons yet — drop SVGs above to begin
        </div>
      )}

      <div className="icon-grid">
        {icons.map((icon) => (
          <div className={`icon-cell ${freshIds.has(icon.id) ? "fresh" : ""}`} key={icon.id}>
            <div className="icon-thumb" dangerouslySetInnerHTML={{ __html: icon.svg }} />
            <div className="icon-info">
              <input
                className="icon-name"
                value={icon.componentName}
                onChange={(e) => updateName(icon.id, e.target.value.replace(/[^a-zA-Z0-9]/g, ""))}
                spellCheck={false}
              />
              <div className="icon-src">{icon.name}.svg</div>
            </div>
            <button
              className="theme-toggle"
              onClick={() => removeIcon(icon.id)}
              title="Remove"
              style={{ fontSize: 10, fontFamily: "var(--mono)", color: "var(--fg-faint)" }}
            >×</button>
          </div>
        ))}
      </div>

      {showIndex && (
        <div style={{ marginTop: 24, display: "flex", flexDirection: "column", gap: 10 }}>
          <div className="section-title">
            <span>index.{indexExt(framework, ts)}</span>
            <button className="toggle-pill" onClick={() => setShowIndex(false)}>Hide</button>
          </div>
          <CodeBlock code={indexSource} lang={framework} />
        </div>
      )}

      <div className="batch-actions">
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-faint)", letterSpacing: "0.04em" }}>
          → generates <span style={{ color: "var(--fg-muted)" }}>icons/index.{indexExt(framework, ts)}</span>, {icons.length} component {icons.length === 1 ? "file" : "files"}, and a README
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button className="btn-secondary" onClick={() => setShowIndex((v) => !v)}>
            {showIndex ? "Hide index file" : "Preview index file"}
          </button>
          <button className="btn-primary" onClick={generateZip} disabled={!icons.length || downloading}>
            {downloaded ? Icon.check : Icon.download}
            <span>{downloading ? "Generating…" : downloaded ? "Downloaded" : "Download icon library"}</span>
          </button>
        </div>
      </div>
    </div>
  );
}
